//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathToolBelt.Sorting.Ui.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MathToolBelt.Sorting.Ui.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image copied to clipboard.
        /// </summary>
        public static string Zedgraph_copied_to_clip {
            get {
                return ResourceManager.GetString("Zedgraph_copied_to_clip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Zedgraph_copy {
            get {
                return ResourceManager.GetString("Zedgraph_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Setup....
        /// </summary>
        public static string Zedgraph_page_setup {
            get {
                return ResourceManager.GetString("Zedgraph_page_setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print....
        /// </summary>
        public static string Zedgraph_print {
            get {
                return ResourceManager.GetString("Zedgraph_print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image As....
        /// </summary>
        public static string Zedgraph_save_as {
            get {
                return ResourceManager.GetString("Zedgraph_save_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Scale to Default.
        /// </summary>
        public static string Zedgraph_set_default {
            get {
                return ResourceManager.GetString("Zedgraph_set_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Point Values.
        /// </summary>
        public static string Zedgraph_show_val {
            get {
                return ResourceManager.GetString("Zedgraph_show_val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Zedgraph_title_def {
            get {
                return ResourceManager.GetString("Zedgraph_title_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo All Zoom/Pan.
        /// </summary>
        public static string Zedgraph_undo_all {
            get {
                return ResourceManager.GetString("Zedgraph_undo_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-Pan.
        /// </summary>
        public static string Zedgraph_unpan {
            get {
                return ResourceManager.GetString("Zedgraph_unpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Scroll.
        /// </summary>
        public static string Zedgraph_unscroll {
            get {
                return ResourceManager.GetString("Zedgraph_unscroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-Zoom.
        /// </summary>
        public static string Zedgraph_unzoom {
            get {
                return ResourceManager.GetString("Zedgraph_unzoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Axis.
        /// </summary>
        public static string Zedgraph_x_title_def {
            get {
                return ResourceManager.GetString("Zedgraph_x_title_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Axis.
        /// </summary>
        public static string Zedgraph_y_title_def {
            get {
                return ResourceManager.GetString("Zedgraph_y_title_def", resourceCulture);
            }
        }
    }
}
